basePath: /v1
definitions:
  models.Order:
    properties:
      createdAt:
        type: string
      customerName:
        example: MNC GOLANG LESSON
        type: string
      id:
        example: 1
        type: integer
      productsId:
        example: 1
        type: integer
      userId:
        example: 1
        type: integer
    type: object
  params.CreateOrder:
    properties:
      customerName:
        type: string
      productId:
        type: integer
    type: object
  views.GetOrderFailedNotFound:
    properties:
      message:
        example: GET_ORDER_NOT_FOUND
        type: string
      status:
        example: 404
        type: integer
    type: object
  views.GetOrderSuccess:
    properties:
      message:
        example: GET_SUCCESS
        type: string
      payload:
        items:
          $ref: '#/definitions/models.Order'
        type: array
      status:
        example: 200
        type: integer
    type: object
host: localhost:4000
info:
  contact:
    email: admin@hacktiv8.com
    name: Hacktiv8
  description: Ini adalah sample API Spec untuk Api orders
  termsOfService: https://swagger.io/terms/
  title: Orders API
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get All orders in detail
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetOrderSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/views.GetOrderFailedNotFound'
      summary: Get All Orders
      tags:
      - orders
  /orders/{id}:
    post:
      consumes:
      - application/json
      description: Create a new Order with input payload
      parameters:
      - description: Create order payload
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/params.CreateOrder'
      - description: path
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: Authorization
        type: string
      - description: X-Token
        in: header
        name: X-Token
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/views.GetOrderSuccess'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/views.GetOrderFailedNotFound'
      summary: Create a new Order
      tags:
      - orders
swagger: "2.0"
