basePath: /
host: localhost:4000
info:
  contact:
    email: yusuf.hasbullah@misteraladin.com
    name: Yusuf Farhan Hasbullah
  description: ini adalah sample api spec untuk To Do List API
  version: "1.0"
paths: {}
swagger: "2.0"
